"""
initial migration

Revision ID: ba82d4a780c1
Revises: e0c31cea8320
Create Date: 2025-07-14 20:40:59.503822

Project   : MyBlog FastAPI System
Author    : Gold Zheng
Alembic   : Auto-generated by Alembic Migration System
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic.
revision: str = 'ba82d4a780c1'
down_revision: Union[str, None] = 'e0c31cea8320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """
    Upgrade migrations:
    Write your upgrade logic here.
    For example:
        op.create_table(...)
        op.add_column(...)
        op.create_index(...)
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade migrations:
    Write your downgrade logic here.
    This is the reverse of upgrade().
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
