"""add view_count to article

Revision ID: f78a29ab6185
Revises: e997a413f07f
Create Date: 2025-07-02 15:19:50.330386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78a29ab6185'
down_revision: Union[str, None] = 'e997a413f07f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles_fts_config',
    sa.Column('k', sa.NullType(), nullable=False),
    sa.Column('v', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('comment',
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('article_id', sa.INTEGER(), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('is_approved', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('summary', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('is_featured', sa.BOOLEAN(), nullable=False),
    sa.Column('has_latex', sa.BOOLEAN(), nullable=False),
    sa.Column('latex_content', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('published_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_article_title', 'article', ['title'], unique=False)
    op.create_table('oauthaccount',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=6), nullable=False),
    sa.Column('provider_user_id', sa.VARCHAR(), nullable=False),
    sa.Column('provider_username', sa.VARCHAR(), nullable=True),
    sa.Column('access_token', sa.VARCHAR(), nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_oauthaccount_provider_user_id', 'oauthaccount', ['provider_user_id'], unique=False)
    op.create_table('articles_fts',
    sa.Column('id', sa.NullType(), nullable=True),
    sa.Column('title', sa.NullType(), nullable=True),
    sa.Column('content', sa.NullType(), nullable=True),
    sa.Column('summary', sa.NullType(), nullable=True),
    sa.Column('author_id', sa.NullType(), nullable=True),
    sa.Column('status', sa.NullType(), nullable=True),
    sa.Column('created_at', sa.NullType(), nullable=True),
    sa.Column('updated_at', sa.NullType(), nullable=True)
    )
    op.create_table('articles_fts_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('block', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles_fts_docsize',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sz', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_file',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=256), nullable=False),
    sa.Column('type', sa.VARCHAR(length=5), nullable=False),
    sa.Column('url', sa.VARCHAR(length=512), nullable=False),
    sa.Column('size', sa.INTEGER(), nullable=False),
    sa.Column('upload_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('uploader_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['uploader_id'], ['user.id'], name='fk_media_file_uploader_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_media_file_id', 'media_file', ['id'], unique=False)
    op.create_table('articles_fts_content',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('c0', sa.NullType(), nullable=True),
    sa.Column('c1', sa.NullType(), nullable=True),
    sa.Column('c2', sa.NullType(), nullable=True),
    sa.Column('c3', sa.NullType(), nullable=True),
    sa.Column('c4', sa.NullType(), nullable=True),
    sa.Column('c5', sa.NullType(), nullable=True),
    sa.Column('c6', sa.NullType(), nullable=True),
    sa.Column('c7', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tag_name', 'tag', ['name'], unique=False)
    op.create_table('mediafile',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=5), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('size', sa.INTEGER(), nullable=False),
    sa.Column('upload_time', sa.DATETIME(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('uploader_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['uploader_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles_fts_idx',
    sa.Column('segid', sa.NullType(), nullable=False),
    sa.Column('term', sa.NullType(), nullable=False),
    sa.Column('pgno', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term')
    )
    op.create_table('articletag',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('article_id', sa.INTEGER(), nullable=False),
    sa.Column('tag_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=9), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('oauth_provider', sa.VARCHAR(length=6), nullable=True),
    sa.Column('oauth_id', sa.VARCHAR(), nullable=True),
    sa.Column('oauth_username', sa.VARCHAR(), nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    # op.create_index('ix_user_email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
